FROM python:3.11

RUN apt-get update && \
    apt-get install -y \
    unzip \
    curl \
    gdal-bin \
    postgis \
    && apt-get clean \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf \
    awscliv2.zip

# WORKDIR /code

WORKDIR /code
COPY api/requirements.txt /tmp/requirements.txt
COPY containers/api/.pgpass /root/.pgpass
RUN chmod 600 /root/.pgpass

RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]